#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

thinkfan_config="$1"

if [ -f "/etc/thinkfan-select/$thinkfan_config.conf" ]; then
	echo "Configuration found, creating symlink..."
	ln -sf /etc/thinkfan-select/$thinkfan_config.conf /etc/thinkfan.conf
	systemctl restart thinkfan
else
	echo "Configuration not found, please choose existing configs."
	ls /etc/thinkfan-select/*.conf | sed -r 's/^.+\///' | sed 's/\.conf$//'
fi
